vim.loader.enable()

require("options")
require("autocommands")
require("diagnostics")

require("plugins")
require("plugins.navigator")
require("plugins.telescope")
require("plugins.treesitter")
-- require("plugins.indentline")
require("plugins.illuminate")
require("plugins.tree")
require("plugins.autopairs")
require("plugins.surround")
require("plugins.comment")
require("plugins.trouble")
-- require("plugins.copilot")
require("plugins.lsp")
require("plugins.cmp")
-- require("plugins.lualine")
-- require("plugins.galaxyline")
require("plugins.go")
require("plugins.neogit")
require("plugins.project")
require("plugins.gitsigns")
require("plugins.ufo")
-- require("plugins.bufferline")
require("plugins.incline")
require("plugins.toggleterm")
-- require("plugins.scrollbar")
require("plugins.notify")
require("plugins.noice")
require("plugins.marks")
require("plugins.smartcolumn")
require("plugins.test")
require("plugins.dap")
require("plugins.zenmode")
require("plugins.colorizer")
require("plugins.hlargs")
require("plugins.crates")
require("plugins.whichkey")
-- require("plugins.chatgpt")
require("keymaps")
require("colorscheme")
