require "options"

require "plugins"
require "plugins.base"
require "plugins.completion"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.indentline"
require "plugins.illuminate"
require "plugins.tree"
require "plugins.autopairs"
require "plugins.lualine"
require "plugins.trouble"
require "plugins.lsp"
require "plugins.comment"
require "plugins.project"

require "keymaps"
require "colorscheme"
