return {
  {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "json5",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "ocaml",
        "haskell",
        "rust",
        "gitignore",
        "gitcommit",
        "toml",
        "make",
        "cmake",
        "c",
        "cpp",
        "go",
        "dockerfile",
        "kotlin",
        "solidity",
        "menhir",
        "ocamllex",
        "func",
        "tact",
      },
    },
  },
}
